#!/usr/bin/env python3

# +------------------------+                       
# | Created with Sailboat  |                       
# |                        |                       
# | Do not edit this file  |                       
# | directly. Insead       |                       
# | you should edit the    |                       
# | `sailboat.toml` file.  |                       
# +------------------------+    

import setuptools

try:
  with open("README.md", "r") as fh:
      long_description = fh.read()
except:
	long_description = "# turtle_test\n\n### Contributors\n- cole\n### Contact\n<cole@colewilson.xyz> "

setuptools.setup(
    name="turtle_test_cole",
    version="1",
		scripts=['bin/turtle_test_cole'],
#		entry_points={
#			'console_scripts': ['turtle_test_cole=turtle_test_cole.__main__.main()'],
#		},
    author="cole",
    author_email="cole@colewilson.xyz",
    description="",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="a.a",
    packages=setuptools.find_packages(),
		install_requires=[],
    classifiers=["Programming Language :: Python :: 3"],
    python_requires='>=3.6',
		package_data={"": [],},
		license="",
		keywords='',
)